# Gradient


In this assignment, we are going to evaluate gradients of the special circuits with the respect to differentiable parameter

In [2]:
import pennylane as qml
from pennylane import numpy as np

In the code cell below, the quantum node is parameterized with {params} 

In [42]:
dev=qml.device('default.qubit', wires=2)
@qml.qnode(dev)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[0, 1])
    qml.PhaseShift(params[2], wires=0)
    return qml.expval(qml.PauliZ(0))

For your first and second graded code you should write a code to evalute gradient with the respect to {params} 


First you should initialize your params and specify them as differentiable parameter 

use {np.random.rand and requires_grad}, then use {qml.grad} to calculate gradient

In [60]:
params=np.random.rand(3,requires_grad=True)
dcircuit=qml.grad(circuit)
dcircuit(params)

array([-6.35190845e-01, -5.55111512e-17,  1.38777878e-17])

In the code cell below, the quantum node is parameterized with {phi,theta}

In [57]:
dev2=qml.device('default.qubit', wires=2)
@qml.qnode(dev2)
def circuit2(phi, theta):
    qml.RX(phi[0], wires=0)
    qml.RY(phi[1], wires=1)
    qml.CNOT(wires=[0, 1])
    qml.PhaseShift(theta, wires=0)
    return qml.expval(qml.PauliZ(0))

Now, you should write a code to evalute gradient with the respect to both {phi,theta}

First you should initialize your params and specify them as differentiable parameter

use {requires_grad} (HINT:initial value for phi and theta are as follows)



phi = [0.5,0.1]



theta=[0.2]




then use {qml.grad} to calculate gradient

In [63]:
# enter your code here 
phi=np.array([0.5,0.1],requires_grad=True)
theta=np.array([0.2],requires_grad=True)
dcircuit=qml.grad(circuit2)

In [62]:
dcircuit(phi,theta)

(array([-4.79425539e-01, -6.93889390e-18]), array([-3.46944695e-18]))

Please pay attention to code cells below 

In [64]:
dev3 = qml.device('default.qubit', wires=2)

@qml.qnode(dev3)
def circuit3(params):
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.PauliY(0)), qml.expval(qml.PauliZ(1))

In [70]:
j1 =qml.jacobian(lambda x: np.stack(circuit3(x)))
j1(params)

array([[-0.64256448, -0.35243165,  0.        ],
       [-0.35243165, -0.64256448,  0.        ]])